import type { Metadata } from 'next'
import { PT_Sans } from 'next/font/google'
import './globals.scss'

const PT = PT_Sans({ weight: ['400', '700'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={PT.className}>{children}</body>
    </html>
  )
}
